### ISSUE TITLE
inside class

### ISSUE THREAD

**Issue by Nahas-N** [websocket-client/websocket-client#707] opened 2021-06-12 12:16 UTC
`error from callback <bound method TickClient.on_open of <__main__.TickClient object at 0x000002A550F52880>>: on_open() takes 1 positional argument but 2 were given
File "D:\InstalledFiles\Anaconda\lib\site-packages\websocket\_app.py", line 407, in _callback
callback(self, *args)`

missing these lines in new version. and call back function inside class makes problem 

` try:
      if inspect.ismethod(callback):
          callback(*args)
       else:
          callback(self, *args)`

https://github.com/websocket-client/websocket-client/blob/11893bc746913f7bfeb85db62dfa6f0c2a1deb6e/websocket/_app.py#L404

**Comment by engn33r** [comment] 2021-06-12 12:49
It looks like the code you are running is for websocket-client before version 0.58.0 and you installed a newer version of websocket-client. This is a duplicate of #669 and solutions are listed in that other issue thread.

**Closed by engn33r** 2021-06-12 12:49 UTC
