### ISSUE TITLE
Error when attempting to run

### ISSUE THREAD

**Issue by jdc4429** [websocket-client/websocket-client#933] opened 2023-07-22 19:52 UTC
Getting the error message below.. Not sure why.  Have not installed websockets or other variations.

Just reinstalled Anaconda completely. Installed all the requirements to base.
Created a new conda environment for Comfy...

Look at this.. when run first time...

(comfy) jeff@jeff-desktop:/var/www/html$ python comfy.py "test" "test" 1920 1080
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
Collecting websocket-client
Obtaining dependency information for websocket-client from https://files.pythonhosted.org/packages/d3/a3/63e9329c8cc9be6153e919e17d0ef5b60d537fed78564872951b95bcc17c/websocket_client-1.6.1-py3-none-any.whl.metadata
Downloading websocket_client-1.6.1-py3-none-any.whl.metadata (7.6 kB)
Downloading websocket_client-1.6.1-py3-none-any.whl (56 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.9/56.9 kB 326.6 kB/s eta 0:00:00
Installing collected packages: websocket-client
Successfully installed websocket-client-1.6.1
Traceback (most recent call last):
File "/var/www/html/comfy.py", line 181, in
ws = websocket.WebSocket()
TypeError: WebSocket.init() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'
(comfy) jeff@jeff-desktop:/var/www/html$

Please see for more info: https://github.com/comfyanonymous/ComfyUI/issues/952

**Comment by engn33r** [comment] 2023-07-24 00:45
The install works fine when installing with pip. Another response in the other issue indicates the problem may be [you have websockets installed](https://github.com/comfyanonymous/ComfyUI/issues/952#issuecomment-1646651757).

**Comment by jdc4429** [comment] 2023-07-24 02:40
I already made it clear I don't. I've done this like 5 times and been using
Linux for 40 years.Work in IT.  It's not something simple.
You obviously didn't read the email.

**Comment by engn33r** [comment] 2023-07-29 14:59
The error message about missing 3 required positional argument doesn't look like an error from websocket-client. There is no argument named "rfile" or "environ" in the source code. I expect this is a conflict with another package or some code is calling websocket-client with incorrect args. Can you share your comfy.py file here, or at least the imports and line 181 triggering the error?

There's a chance the issue is in the conda package of websocket-client, though I find that unlikely https://github.com/conda-forge/websocket-client-feedstock

**Comment by engn33r** [comment] 2023-07-30 16:11
The past month has seen several issues opened from conda users. To help identify if there is a pattern, please answer the following:
1. If you are installing websocket-client as a dependency, what is the package that requires this dependency?
2. Which version of websocket-client have you installed? One way to check is with `import websocket` and `websocket.__version__`
3. Which Python version are you using and on which OS?
4. Do you have a similarly named package like [websockets](https://github.com/python-websockets/websockets) installed?

**Comment by jdc4429** [comment] 2023-07-30 17:44
Sorry, i was on Ubuntu but my system crashed so ported to Windows. No
longer have info.

**Comment by engn33r** [comment] 2023-07-30 18:48
Ok I will close this issue if it's no longer a problem, but I can reopen if there's more information that can help with determining the root cause

**Closed by engn33r** 2023-07-30 18:48 UTC
