### ISSUE TITLE
Multithreading issue with pings from server

### ISSUE THREAD

**Issue by fischercer** [websocket-client/websocket-client#507] opened 2018-11-27 09:33 UTC
I think there is a multithreading issue when using the WebSocketApp. 

As the App activates locking only if the interval timer is set:
`enable_multithread=True if ping_interval else False`

Pongs to server initiated Pings would be sent without locking and therefore cause connection interrupts and _ssl.c errors which are very hard to debug. 
The correct behavior would be to always activate locking when the WebSocketApp is used. As the standard requires that pings are automatically answered and the App acts as high level API.

**Comment by engn33r** [comment] 2021-06-04 01:22
I don't see any downsides to setting `enable_multithread=True` by default, but we'll see if I overlooked something. Commit beb135a fixes this. Duplicate of #591.

**Closed by engn33r** 2021-06-04 01:22 UTC
