### ISSUE TITLE
Websocket reconnect infinite loop

### ISSUE THREAD

**Issue by fhriley** [websocket-client/websocket-client#889] opened 2023-01-19 23:50 UTC
There is something not quite right with the reconnect loop. It gets stuck in this infinite loop:

```
2023-01-19 16:46:40.951326-0700 kodi.bin[78503:22543224] 2023-01-19 16:46:40.951 T:22543224    info <general>: INFO|websocket|_logging.py:74|t:Thread-1 (ws_app_loop)|reconnect() - retrying in 1 seconds [8 frames in stack]
2023-01-19 16:46:42.045568-0700 kodi.bin[78503:22543224] 2023-01-19 16:46:42.045 T:22543224 warning <general>: WARNING|websocket|_logging.py:66|t:Thread-1 (ws_app_loop)|websocket connected
2023-01-19 16:46:42.046741-0700 kodi.bin[78503:22543224] 2023-01-19 16:46:42.046 T:22543224    info <general>: INFO|websocket|_logging.py:74|t:Thread-1 (ws_app_loop)|reconnect() - retrying in 1 seconds [8 frames in stack]
2023-01-19 16:46:43.167292-0700 kodi.bin[78503:22543224] 2023-01-19 16:46:43.167 T:22543224 warning <general>: WARNING|websocket|_logging.py:66|t:Thread-1 (ws_app_loop)|websocket connected
2023-01-19 16:46:43.167967-0700 kodi.bin[78503:22543224] 2023-01-19 16:46:43.167 T:22543224    info <general>: INFO|websocket|_logging.py:74|t:Thread-1 (ws_app_loop)|reconnect() - retrying in 1 seconds [8 frames in stack]
2023-01-19 16:46:44.286507-0700 kodi.bin[78503:22543224] 2023-01-19 16:46:44.286 T:22543224 warning <general>: WARNING|websocket|_logging.py:66|t:Thread-1 (ws_app_loop)|websocket connected
2023-01-19 16:46:44.287750-0700 kodi.bin[78503:22543224] 2023-01-19 16:46:44.287 T:22543224    info <general>: INFO|websocket|_logging.py:74|t:Thread-1 (ws_app_loop)|reconnect() - retrying in 1 seconds [8 frames in stack]
2023-01-19 16:46:45.418532-0700 kodi.bin[78503:22543224] 2023-01-19 16:46:45.418 T:22543224 warning <general>: WARNING|websocket|_logging.py:66|t:Thread-1 (ws_app_loop)|websocket connected
2023-01-19 16:46:45.419989-0700 kodi.bin[78503:22543224] 2023-01-19 16:46:45.419 T:22543224    info <general>: INFO|websocket|_logging.py:74|t:Thread-1 (ws_app_loop)|reconnect() - retrying in 1 seconds [8 frames in stack]
```

The websocket on the server side is ok because while this infinite loop is happening, I can connect to it with another app with no issues.

This is how I'm running the client:

```python
    try:
        wsapp.run_forever(reconnect=1)
    except Exception:
        log.exception('wsapp.run_forever() failed')
```

Version 1.4.2.

**Comment by engn33r** [comment] 2023-01-26 09:32
The issue should be resolved with version 1.5.0, which includes a fix from PR #862

This issue is a duplicate of #891

**Closed by engn33r** 2023-01-26 09:32 UTC
