### ISSUE TITLE
License preferences for possible migration?

### ISSUE THREAD

**Issue by engn33r** [websocket-client/websocket-client#665] opened 2021-02-23 02:44 UTC
This project experienced some [messy license switches](https://github.com/websocket-client/websocket-client/issues/526#issuecomment-780736307) (see issue #526 for more details) and it would be nice to get all contributors to agree to a final change of open source license. I am no expert on the pros/cons of different open source licenses, so I opened this issue to initiate discussions around which license users would most prefer this code to be under. Assuming that the LGPL v2.1 license is not the preferred choice and an alternative consensus is reached, I can begin the process of trying to get all contributors to agree to this switch.

So which license do you think would enable the most flexibility for this project's future?

**Comment by penrods** [comment] 2021-02-23 06:30
To kick this off I'll toss out my summary of license categories.  Then we can look at specific licences to meet the desired category.

## Extremely permissive
The most famous of these is the MIT license.  Virtually no limitations, code is can be used freely and without any credit or acknowledgement.

PRO: Anyone can build on top of it -- corporations, governments, individuals, other projects under any license.
CON: Lack of acknowledgement is possible.  Can be used in closed source projects.

## Permissive
Licenses like Apache and BSD.  The software can be used with virtually no limitation, but generally must be acknowledged in the credits.

PRO: Virtually anyone can build on top of it.  This project will always receive acknowledgement.
CON: Can be used in a closed-source project.

## Copyleft
The GPL family of licenses.  There is a range from LGPL to GPL to Affero GPL and Mozilla Public License (MPL).  These licenses require works with use the licensed code to also publish their own code using a GPL license.  Technically, the code must only be published to the users of the software, but practically speaking it involves publishing the source code on the web somewhere public.

PRO: Encourages/requires that project using this are also open source (and often the same license).
CON: Practically excludes most corporate use.  Also excluded from certain highly regulated uses, like medical equipment.


That is a super brief summary, but covers the main licenses people know of.  There are some subtleties to all licenses, but I'd recommend the debate be limited to one of these three:  MIT, Apache 2.0, LGPL 2.1

---

Above the line I tried to be factual.  Now I'll give some opinion (based on gray-beard experience).  

There are certainly other licenses that are worthy, but MIT, Apache 2.0 and LGPL 2.1 these three are very well known and accepted (for example [the French government has acknowledged these as legit](https://www.data.gouv.fr/en/licences)).  I'd be happy to discuss an alternative if someone has a a strong preference for something like MPL or BSD, but I don't see huge benefit from straying away from the most popular for this project.

LGPL can and will limit the project adoption by some, and apparently there was desire to move away from it and towards more open license during the first attempt at re-licensing.  Being permissive didn't seem to harm the project in the years since 2018 (even it if wasn't legit), it might have even increased it's popularity.

Permissive licenses like Apache are a good balance for Open Source advocates and well accepted by industry.  I personally like the Apache 2.0 license over BSD a little more because of the explicit language addressing patents.  It has also held up well in legal rulings.

The MIT license really is the easiest for everyone to digest and use.  I wouldn't be opposed to backing that, but I don't know if that level of permissiveness gains the project much.

So my vote:  Apache 2.0


One other item to at least consider at this point is instituting some form of contributors agreement.  A CLA allows the project maintainers to make future decisions for the community of contributors and avoids the difficult task of getting permissions for each individual contributor.  Of course, that difficulty can also be seen as a benefit -- a rogue maintainer cannot simply make changes willy-nilly or abuse the community by doing things like converting the project into a for-profit venture.  Some contributors are also put-off by the thought of signing away their rights.  And maintaining a CLA is a minor hassle, although there are some tools that automate it nowadays.

**Comment by xloem** [comment] 2021-02-23 07:24
I do not intend to bias this project towards any particular kind of license.  I am idealistically biased towards copyleft.

> CON: Practically excludes most corporate use. Also excluded from certain highly regulated uses, like medical equipment.

I do not believe that GPL excludes medical equipment: https://www.fsf.org/blogs/licensing/gplv3-fda

I'll delete this post if you update yours, to not clog the thread.

**Comment by gonzalocasas** [comment] 2021-02-28 09:10
@penrods thanks for the great overview.

Perhaps I would question whether "Can be used in a closed-source project" is a negative one, but this is borderline philosophical, so I understand why you listed in there.

In any case, I agree with the preference for Apache 2.0 as the best balance between permissiveness, acknowledgement and protection against patent issues.

**Comment by xloem** [comment] 2021-02-28 15:25
Note: LGPL is not copyleft and does not require developers using the library to share their project source code.

**Comment by gonzalocasas** [comment] 2021-02-28 15:54
It's a compromise over the strong copyleft of GPL, but it is copyleft still (from [wikipedia](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License)): 
![image](https://user-images.githubusercontent.com/933277/109424773-79087080-79e5-11eb-87c4-53933b8e2927.png)

**Comment by wavenator** [comment] 2021-05-02 07:23
Is this issue still being considered? I would like to add that choosing a permissive license allows organizations (like mine for example) to use it as part of our backend. To many open-source contributors, it seems like allowing organizations to use it without releasing their code is ungratefulness but people forget that we release many open-source projects ourselves, and we do that under permissive licenses such as MIT. I hope you will choose a permissive license so we can use your project. I know that many organizations contribute to open-source projects and support many too.

**Comment by engn33r** [comment] 2021-05-02 19:07
The license change is still being considered, so thank you for leaving your thoughts. I plan to reach a conclusion on this topic by May 15th. After a license has been chosen on that date, we can kick off the transition process to that license.

**Comment by engn33r** [comment] 2021-05-12 01:09
To summarize where I see things currently as project maintainer, the previous comments are leading me to the conclusion that the Apache 2.0 license is the rough consensus of what the contributors/users who have commented above would prefer this project to use. I am in favor of this approach too. If there are any users or contributors who have strong feelings otherwise, please speak up! I am planning to start taking steps to make this transition to Apache 2.0 happen in roughly the next week or so.

**Comment by Marenthyu** [comment] 2021-05-22 08:52
I'm happy to see an active community around a project, even if my contribution to it was only as minor as a couple commits a bunch of years ago.

Personally, I like to use BSD-3 for my own projects as it's easy to quickly understand, even if you haven't read any license before - but other Licenses are surely more thorough in their descriptiveness, so I see nothing wrong with these changes and approve of it (as confirmed by my comment on the other issue.)

Funnily enough, this repo was so far the first and only one i contributed to (and do not own myself) that caused someone to mail me directly and ask some questions. (YEARS after my contribution!) It's heartwarming to know that there are people that care and utilize the tools that open source grants us.

Keep this good chunk of software free, I appreciate it!

**Comment by graingert** [comment] 2021-05-22 10:58
You tagged @ghost in your list of contributors - this isn't a real account and just a placeholder for deleted accounts. You'll need to find out the specific commits that are assigned to deleted accounts and contact them directly

**Comment by apple314159** [comment] 2021-05-22 11:53
Yes, I consent to the change to the Apache 2.0 license

**Comment by graingert** [comment] 2021-05-22 15:26
> Yes, I consent to the change to the Apache 2.0 license

@apple314159 this is the wrong thread

**Comment by engn33r** [comment] 2021-05-22 16:43
@graingert thank you for catching this, I didn't know ghost was a placeholder. The contribution was a very minor typo fix in PR #286. I will send an email to Richard using the email from `git log`, but since this typo fix was so minor and others also pointed it out, I'll remove @ghost from the list for now.

**Comment by minus7** [comment] 2021-05-30 23:32
I don't appreciate being spammed about this. Imo, you should have picked and stuck with a compatible license (probably LGPL3, since that's what all contributions are compatible with).

**Comment by Marenthyu** [comment] 2021-05-31 11:40
> I don't appreciate being spammed about this. Imo, you should have picked and stuck with a compatible license (probably LGPL3, since that's what all contributions are compatible with).

You can click any of the unsubscribe links at the bottom of the Emails you receive, but every contributor needs to be notified about the change, so if you are annoyed by the "spam", I suggest you check your GitHub notification settings.

And sorry to those that got a notification for this comment as well ;)

**Closed** 2021-08-11 01:51 UTC
