### ISSUE TITLE
Problems using websocket-client in docker

### ISSUE THREAD

**Issue by ekimia** [websocket-client/websocket-client#302] opened 2017-02-25 22:13 UTC
Is there any known issues using `websocket-client` with docker? I do have the port open but still can't connect.

**Comment by engn33r** [comment] 2021-02-15 04:12
Both Docker and this library have changed a lot since the date that this issue was written. I'm going to close this issue for now due to the lack of details around what the issue is, but if an issue using this library with Docker occurs in the future, please create a new issue with additional details.

**Closed by engn33r** 2021-02-15 04:12 UTC
