### ISSUE TITLE
Use IP address instead of hostname

### ISSUE THREAD

**Issue by and7ey** [websocket-client/websocket-client#601] opened 2020-02-04 19:37 UTC
Looks like I can not pass an IP address to `ws.connect()`. If the IP address (wss://95.123.123.123) is passed, then I see the following error:
```
File "/base/data/home/apps/my-app.py", line 115, in send_text
    ws.connect(str(device_address))
  File "libs/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "libs/websocket/_http.py", line 121, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "libs/websocket/_http.py", line 186, in _open_socket
    eConnRefused = (errno.ECONNREFUSED, )
DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded.
```
But it works fine if hostname (like `wss://something.example.com`) pointing to the same address is passed instead.

(the client is running on Google App Engine)

**Comment by engn33r** [comment] 2021-02-15 04:53
I think this may be a duplicate of (or related to) #602. I am able to use an IP address to establish a connection, so this may be a Google App Engine issue. Closing for now, but reopen if the issue is still there and possible to recreate outside of Google App Engine.

**Closed by engn33r** 2021-02-15 04:53 UTC
