### ISSUE TITLE
Multiple on_open events

### ISSUE THREAD

**Issue by NadavK** [websocket-client/websocket-client#971] opened 2024-02-25 23:24 UTC
Client receives an occasional second `on_open` callback, even though I did not actively re-open a connection, not did I receive an `on_close` or `on_error` callback.
The `on_close` and `on_error` callbacks _do_ get fired at other times, so the problem is not a mistake in my callback function/log.
Using v1.7.0.

client-side log:
22:13:02 - ws opened (<websocket._app.WebSocketApp object at 0xffff98662250>)
22:13:02 - ws sending: {msg 1...}
22:13:20 - ws sending: {msg 2...}
22:19:52 - ws on_ws_error Connection to remote host was lost. (<websocket._app.WebSocketApp object at 0xffff98662250>)
22:21:04 - ws opened (<websocket._app.WebSocketApp object at 0xffff98662250>)
22:38:52 - ws opened (<websocket._app.WebSocketApp object at 0xffff98662250>)
23:07:47 - ws closed: close_status_code: None, close_msg: "None" (<websocket._app.WebSocketApp object at 0xffff98662250>)

server side log (Django channels):
22:13:02 - connected _(correlates to client `on_open`)_
22:19:52 - disconnect _(correlates to client `on_error`)_
22:21:04 - connected _(correlates to client `on_open`)_
22:38:52 - connected _(correlates to client second `on_open`)_
22:39:15 - disconnect _(no client correlation)_
23:07:47 - disconnect _(correlates to client `on_close`)_

This behavior affects my server-side client-status, since the disconnect at 22:39:15 sets the server-side status to "not-connected", even though there is still an active connection and data sent by the server is still received by the client.
I can solve it by using a reference count on the server, but in any case the client behavior seems odd...

**Comment by bubbleboy14** [comment] 2024-02-26 01:10
Looks like this line should be conditionalized: https://github.com/websocket-client/websocket-client/blob/a394b46c560cb78672f95bbb3836305e8511d1b9/websocket/_app.py#L500

What do you think @engn33r ? For starters, we could just set a flag the _first_ time _callback(on_open) gets called from setSock(), and not call it subsequent times.

Also, though, since there are probably _some_ applications that would want on_open() called more than once (presumably here on reconnects), I think it might be nice to add a kwarg flag to run_forever() to specify whether or not on_open should only be called the first time.

Or (and this might be cleaner) we could add an on_reconnect() callback? And setSock() could just call on_open() the first time and on_reconnect() from then on. I think I like that approach most.

Thoughts?

**Comment by NadavK** [comment] 2024-02-26 07:36
@bubbleboy14, it seems that the problem is not that `on_open` is called twice, but rather that the library seems to actually open a second connection while the first one is still active.
Notice that both the client and server log a second created connection at 22:38:52, without an intervening disconnect between them?

**Comment by NadavK** [comment] 2024-02-26 08:24
Something interesting I noticed, is that this behavior of multiple `on_open` only occurs after an error event "Connection to remote host was lost".
The time between the first `on_open` (after the error) and the next consecutive `on_open` is not consistent (ranges from 2 minutes to 2 hours).

**Comment by bubbleboy14** [comment] 2024-02-26 20:59
I made a branch: https://github.com/websocket-client/websocket-client/tree/t971

It just uses setSock()'s reconnecting kwarg to decide between on_open and on_reconnect callbacks. @NadavK I hope this helps shed light on the issue you're debugging.

@engn33r in any case, I think this would be an improvement, as many applications would probably need to distinguish between these cases. For instance, it's logical to run initialization code on_open that you wouldn't want to run again on_reconnect.

**Comment by NadavK** [comment] 2024-02-26 21:33
Thank you for you quick response.
Your suggestion does improve the application-side logic.

But please note, that my issue is less with differentiating between `open` and `reconnect`, and more with the fact that the client seems to create an additional connection while the previous connection is still functional.

**Comment by bubbleboy14** [comment] 2024-02-27 03:14
@NadavK if you have a minimal test case (ideally client and server) that reproduces this issue, I can take a look.

**Comment by bubbleboy14** [comment] 2024-03-01 03:47
I tweaked that branch to preserve the current behavior (of calling on_open on reconnect) unless on_reconnect is defined, and made a PR: https://github.com/websocket-client/websocket-client/pull/972

@engn33r what are your thoughts? I'm starting to realize I need that distinction (on_open vs on_reconnect) for something I'm building.

@NadavK I have a hunch it's not actually opening a second connection, but instead reconnecting (which triggers on_open) without calling on_close (because it reconnected). I think on_open is just overloaded, and that's what's confusing. If you try that branch (and add an on_reconnect callback to your code) your logs might make more sense. Maybe/hopefully anyway.

LMK what you guys think!

**Comment by NadavK** [comment] 2024-03-11 21:51
So it seems the server-side 'repeated' disconnects issue only occurs with Cloudflare: when routing websocket-client directly to the server (and not via Cloudflare), I did not observe any 'repeated' disconnects on the server-side.
Sorry to have troubled you @bubbleboy14!

**Comment by engn33r** [comment] 2024-04-23 22:18
This should be fixed in v1.8.0 which includes PR #972. If this reoccurs, we can reopen the issue.

**Closed by engn33r** 2024-04-23 22:18 UTC
