### ISSUE TITLE
could you answer my question that how to send a long message?

### ISSUE THREAD

**Issue by Igoslow** [websocket-client/websocket-client#633] opened 2020-09-01 01:50 UTC
when i send a long message, the problem that websocketconnectionclosed has occurred.

**Comment by Igoslow** [comment] 2020-09-01 01:52
The massage has about 5000 characters long

**Comment by Igoslow** [comment] 2020-09-01 01:55
The massage has about 5,000 to10,000 characters long. This method causes the connection to close.

**Comment by chwba** [comment] 2020-09-01 12:25
this lib is dead, dont bother

**Comment by engn33r** [comment] 2021-02-16 16:53
@Igoslow thanks for highlighting this issue. It looks like this is a duplicate of #603. Could you post [the debug trace](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) of your connection to issue #603? It will help us keep the information about this issue in one place.

I am going to close this issue for now since I believe it is a duplicate of #603, but I am happy to continue the discussion there.

**Closed by engn33r** 2021-02-16 16:53 UTC
