### ISSUE TITLE
Issue when system loses network connection

### ISSUE THREAD

**Issue by gidim** [websocket-client/websocket-client#807] opened 2022-03-30 18:31 UTC
Hi,
We're using websocket-client to send small messages in a fairly high throughput. We're currently experiencing an issue when the following happens (using run_forever())

1. Send many messages in a loop
2. Manually terminate internet connection of the system
...TIMEOUT period...
3. Socket timeout is being called in our application logic and reconnect kicks in.

The issue is that essentially everything that was sent after the connection was terminated but before the timeout is lost. Our suspicion is that those frames are stored in the OS TCP buffer and once close() is called the buffer is cleared. Our expectation is that when the system loses connection an exception would be raised that will allow us to stop sending messages. 

I've seen some related issues here and was wondering if you might have an idea of how to resolve this!

Thanks

**Comment by engn33r** [comment] 2022-04-01 20:32
I have not tested edge cases with many combined factors, like high data throughput + many connections + timeout + disconnections. You have probably seen issues such as #786 and some others discussing this. The most I have looked at the buffer storage [is mentioned here](https://github.com/websocket-client/websocket-client/issues/622#issuecomment-852606544).

I will leave this issue open for a while in case someone else has ideas. I think you need to determine where the issue is and where (or if) the data is being stored in a buffer. This issue could be at the OS networking layer, in websocket-client, or somewhere else.

If you find a solution, share the knowledge and let us know!

**Comment by adamwojt** [comment] 2022-07-27 13:05
I am facing similar issue.

When disabling internet connection after timeout delay exception is raise `WebSocketTimeoutException("ping/pong timed out")`.

But there is short window of time between disconnect and `WebSocketTimeoutException` when messages do get sent without exception even though connection is clearly lost.

I tested with monkey patching `send` method and return of `self.sock.send(data, opcode)` in code below is `244` which is same as when there is internet connection.
https://github.com/websocket-client/websocket-client/blob/61171591b08ee031e02cc6cb129952259062f502/websocket/_app.py#L190-L205

**Comment by engn33r** [comment] 2022-08-24 19:08
Release 1.4.0 has PR 838 merged, which improve `run_forever` and might help with this issue. I will close this for now, but if you confirm that this is still a problem with release 1.4.0, I will reopen it for deeper investigation.

**Closed by engn33r** 2022-08-24 19:08 UTC
