### ISSUE TITLE
websocket logs: close status: 23419, but not calling on_close

### ISSUE THREAD

**Issue by tesla1060** [websocket-client/websocket-client#452] opened 2018-07-16 08:43 UTC
Hi, 
I am using 0.48.0, python 2.7. It seems when connection is closed, due to some unknown reason, sometimes, `on-close` is called, so that I can do a reconnect, but sometimes, `on_close` is not called and `on_error` is not called either. 

The way I am using it something looks like this,

        self.ws = websocket.WebSocketApp(self.host,
                                         on_message=self.onWsMessage,
                                         on_error=self.onWsError,
                                         on_close=self.onWsClose,
                                         on_open=self.onWsOpen,
                                         on_pong=self.onWsPong
                                        )
        self.wsThread = Thread(target=self.ws.run_forever,
                               kwargs=dict(
                                   ping_interval=self.pingInterval,
                                   ping_timeout=self.pingTimeOut,
                                   http_proxy_host=httpProxyHost,
                                   http_proxy_port=httpProxyPort
                               ))
        self.wsThread.start()

**Comment by engn33r** [comment] 2021-05-07 01:48
@ tesla1060 @victorlaurens if either of you are still actively using this project, it would be great to know if the latest master branch solves this issue. In issue #686 I explained how the on_close callback code had an issue that has existed for a long time, but I think this was fixed (or at least improved) by commit c414127.

**Comment by engn33r** [comment] 2021-05-18 02:16
Closing due to likelihood that the issue is fixed in the latest release, possibly with commit c414127. If this issue reoccurs, please create a new issue with the information outlined in the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md).

**Closed by engn33r** 2021-05-18 02:16 UTC
