### ISSUE TITLE
Stuck at "Connection established"

### ISSUE THREAD

**Issue by distance00** [websocket-client/websocket-client#613] opened 2020-04-04 16:01 UTC
Using websocket.WebSocketApp, every few minutes close and reopen, running six hours happened twice, no error, no timeout, no nothing. Stuck at 

--- response header ---
HTTP/1.1 200 Connection established

Im using os.environ['http_proxy'] to set proxy, don't know if it matters.

**Comment by distance00** [comment] 2020-04-04 16:22
Did I get an empty response? normally it's followed with another request header, and then another response, on and on "forever".

**Comment by distance00** [comment] 2020-04-04 16:45
It doesn't seem to be the case, no message received at that step.

**Comment by RichardFoo** [comment] 2020-05-21 00:34
I've seen similar with 0.57.0.  Connection establishes, but the on_open event doesn't get triggered on the client side.  Falling back to 0.47.0 fixed the problem for the moment.

**Comment by engn33r** [comment] 2021-02-23 03:55
If either of you (@distance00 or @RichardFoo) are still using this project, would you mind checking if the latest code in the master branch resolves your issue? I am optimistic that commit 3112b7d fixed issues that have persisted since release 0.48.0 (see the comment on that commit for the reasoning around it), but if this issue still exists with the latest master release, then there's something more at work in this issue that I don't yet understand

**Comment by jeteon** [comment] 2021-04-08 06:59
In my case the issue persisted but it turned out to be because the signature of the callbacks changed at some point. Once I modified the callbacks to take the websocket instance as the first argument, things started working again. I'm not sure why it didn't call it and run into some error though.

**Comment by engn33r** [comment] 2021-04-30 01:29
I a not exactly sure what the issue is here, but if someone encounters this problem in the future, please include more information as described in the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question) so we can try and get to the bottom of this. I will close this for now with the assumption that it was either a system-specific error or something that has been fixed more recently in this library.

**Closed by engn33r** 2021-04-30 01:29 UTC
