### ISSUE TITLE
how can i add sockets5  in  this model

### ISSUE THREAD

**Issue by CL545740896** [websocket-client/websocket-client#488] opened 2018-09-23 08:48 UTC
import websocket
try:
    import thread
except ImportError:
    import _thread as thread
import time

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def on_open(ws):
    def run(*args):
        for i in range(3):
            time.sleep(1)
            ws.send("Hello %d" % i)
        time.sleep(1)
        ws.close()
        print("thread terminating...")
    thread.start_new_thread(run, ())

if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("ws://echo.websocket.org/",
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    ws.on_open = on_open
    ws.run_forever()

**Comment by engn33r** [comment] 2021-02-15 03:59
Unfortunately I don't understand your exact question, but I can see two possible approaches. If you are looking for more example code, check the newly created [Examples documentation](https://websocket-client.readthedocs.io/en/latest/examples.html) to see if it can help you. If you are actually referring to using a SOCKS5 proxy (the title of this issue says "sockets5" not "SOCKS5"), then this issue is a duplicate of #362. I will close this issue for now, since I think these two answers should help, but if I didn't understand your question, then you can reopen this issue and add further detail.

**Closed by engn33r** 2021-02-15 03:59 UTC
