### ISSUE TITLE
automatically send unknown message

### ISSUE THREAD

**Issue by Actoress** [websocket-client/websocket-client#578] opened 2019-10-24 09:11 UTC
I didn't send anything
but look at the console, it sent the following contents
```
send: b'\x89\x80\xadt\t\xff'
send: b'\x89\x80\x88ZL\xde'
send: b'\x89\x802X\xdd\xeb'
send: b'\x89\x80\xd52H\x84'
send: b'\x89\x80\xe3e\xed\xe7'
send: b'\x89\x80\xeb\xbf\x00\x89'
send: b'\x89\x80\x1a\x9c\xf6\xd8'
send: b'\x89\x80\xcf\x8cb\xba'
send: b'\x89\x80\xa4\xa1\xd9\xb7'
send: b'\x89\x80C$j\xd8'
send: b'\x89\x80\xed\x15\xf7\x9d'
send: b'\x89\x80\xa08\x0f\x82'
send: b'\x89\x80R\x88\xd7\xfd'
send: b'\x89\x80\xc4\x19M\xce'
```

**Comment by ebirbe** [comment] 2020-04-24 18:02
I'm having similar output everytime I send something, but looking at the code I cannot see where it is generated or where could it be disabled.

Where should I look at in order to avoid this kind of output messages?

**Comment by ebirbe** [comment] 2020-04-24 18:10
Forget it, I found the solution here at https://github.com/websocket-client/websocket-client/issues/550

**Comment by engn33r** [comment] 2021-02-20 03:02
Looks like a duplicate of 550, but for future reference, the functionality of websocket.enableTrace(True) is now in [the project documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) to help future users

**Closed by engn33r** 2021-02-20 03:02 UTC
