### ISSUE TITLE
Client Can Stop Pinging Indefinitely

### ISSUE THREAD

**Issue by mhconradt** [websocket-client/websocket-client#820] opened 2022-05-09 14:26 UTC
Print statements are my own, added to `1.3.2`:
```
        while not event.wait(interval):
            print("trying to ping")
            self.last_ping_tm = time.time()
            if self.sock:
                try:
                    self.sock.ping(payload)
                    print("ping did work")
                except Exception as ex:
                    print("ping did not work")
                    _logging.warning("send_ping routine terminated: {}".format(ex))
                    break
        print("stopped trying to ping")
```
Essentially, `event.wait(interval)` can return `True`, and then the `WebsocketApp` stops pinging indefinitely, then the server stops sending new data after a couple minutes.
If you're curious or it matters, my ping_interval is set to 15 seconds.

**Comment by engn33r** [comment] 2022-05-09 18:57
This looks like a duplicate of #816. If your issue is different, please share the outputs or [a debug trace](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) so we can see what behavior is happening.

**Closed by engn33r** 2022-05-09 18:57 UTC

**Comment by mhconradt** [comment] 2022-05-10 13:23
@engn33r the difference is that in my case `self.sock.ping(payload)` is not throwing an exception. Here are some logs from my application:
```
2022-05-10T13:17:21.202Z | INFO | __main__:realtime_ingest_tickers:62 | Writing 428 tickers
2022-05-10T13:17:21.340Z | INFO | __main__:realtime_ingest_tickers:69 | Writing 428 tickers (done)
2022-05-10T13:17:21.348Z | INFO | __main__:realtime_ingest_tickers:62 | Writing 438 tickers
trying to ping
ping did work
2022-05-10T13:17:21.450Z | INFO | __main__:realtime_ingest_tickers:69 | Writing 438 tickers (done)
2022-05-10T13:17:21.456Z | INFO | __main__:realtime_ingest_tickers:62 | Writing 479 tickers
2022-05-10T13:17:21.598Z | INFO | __main__:realtime_ingest_tickers:69 | Writing 479 tickers (done)
...
2022-05-10T13:17:28.184Z | INFO | __main__:realtime_ingest_tickers:69 | Writing 351 tickers (done)
2022-05-10T13:17:28.191Z | INFO | __main__:realtime_ingest_tickers:62 | Writing 426 tickers
stopped trying to ping
2022-05-10T13:17:28.303Z | INFO | __main__:realtime_ingest_tickers:69 | Writing 426 tickers (done)
2022-05-10T13:17:28.311Z | INFO | __main__:realtime_ingest_tickers:62 | Writing 448 tickers
2022-05-10T13:17:28.379Z | INFO | __main__:realtime_ingest_tickers:69 | Writing 448 tickers (done)
2022-05-10T13:17:28.387Z | INFO | __main__:realtime_ingest_tickers:62 | Writing 417 tickers
...
2022-05-10T13:17:44.950Z | INFO | __main__:realtime_ingest_tickers:62 | Writing 540 tickers
2022-05-10T13:17:45.059Z | INFO | __main__:realtime_ingest_tickers:69 | Writing 540 tickers (done)
2022-05-10T13:17:46.067Z | INFO | __main__:realtime_ingest_tickers:62 | Writing 144 tickers
2022-05-10T13:17:46.222Z | INFO | __main__:realtime_ingest_tickers:69 | Writing 144 tickers (done)

Process finished with exit code 0
```
Note that:
1. The "stopped trying to ping" message happens after only seven seconds.
2. It was not directly preceded by a "trying to ping".
3. There was no "ping did not work" message.

**Comment by mhconradt** [comment] 2022-05-10 13:44
I didn't realize the server was sending a close frame, so the library is working as expected, my bad.
