### ISSUE TITLE
xml-not-well-formed after only two messagens and last one same than fist

### ISSUE THREAD

**Issue by mmm286** [websocket-client/websocket-client#636] opened 2020-09-07 23:15 UTC
Hi,
In my code:

    ws.send("<open xmlns=\"urn:ietf:params:xml:ns:xmpp-framing\" version=\"1.0\" xml:lang=\"en\" to=\"wallapop.com\"/>")
    ws.send("<auth xmlns=\"urn:ietf:params:xml:ns:xmpp-sasl\" mechanism=\"PLAIN\">xxxxxxxxxxxxxxx</auth>")
    ws.send("<open xmlns=\"urn:ietf:params:xml:ns:xmpp-framing\" version=\"1.0\" xml:lang=\"en\" to=\"wallapop.com\"/>")

And it gives me:

```
message received ..
<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>
message received ..
<stream:error><xml-not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
message received ..
</stream:stream>
```
Any help please? Thanks

**Comment by engn33r** [comment] 2021-01-26 02:54
Duplicate of #635

**Closed by engn33r** 2021-01-26 02:54 UTC
