### ISSUE TITLE
Hangs on long running sockets that never time out

### ISSUE THREAD

**Issue by sdague** [websocket-client/websocket-client#437] opened 2018-06-04 14:46 UTC
I've been using websocket-client as the basis for sdague/waterfurnace (an interface for the online data platform for waterfurnace geothermal systems). They communicate over a websocket, but in order to gather data you have to send a request over it.

The code effectively does:

        self.ws = websocket.create_connection(
            "wss://awlclientproxy.mywaterfurnace.com/", timeout=TIMEOUT)
       
Then from inside a dedicated thread, it does a loop of:

            self.ws.send(json.dumps(req))
            data = self.ws.recv()

After some number of days (from a couple to a couple of weeks), the recv() will just hang. The TIMEOUT is set to 30, so I had assumed that it would throw an exception and move on after 30 seconds. But it does, it just stays hung until I restart the process.

This is using 0.47, but I've seen the behavior in earlier versions as well.

Any ideas on how to make the timeouts be respected? or if there is an underlying bug here?

**Comment by shr00mie** [comment] 2018-07-09 23:18
i've been having a similar issue. websocket runs fine and reconnects under normal circumstances over ~2-3 days, but i can't get it running longer than that. turned enableTrace on to see if i can get some more info from the failure.

**Comment by digdig** [comment] 2019-06-19 05:58
Hi, I also find that sometimes `ws.recv()` will hang indefinitely, did you solve this problem? I am using version `0.56`

**Comment by digdig** [comment] 2019-06-19 06:49
In the source code, I found a thread lock, could anyone see if somehow it will lead to a deadlock?

```
    def recv(self):
        """
        Receive string data(byte array) from the server.
        return value: string(byte array) value.
        """
        with self.readlock:
            opcode, data = self.recv_data()
        if six.PY3 and opcode == ABNF.OPCODE_TEXT:
            return data.decode("utf-8")
        elif opcode == ABNF.OPCODE_TEXT or opcode == ABNF.OPCODE_BINARY:
            return data
        else:
return ''
```

**Comment by digdig** [comment] 2019-06-19 07:46
#523

**Comment by 18969927785** [comment] 2019-08-09 03:56
> some related issues: #523 #290 #24 #48 #356

hi,
  do you solve the problem now, I have the same problem and it troubles me.

**Comment by andresriancho** [comment] 2019-11-18 11:08
The issue seems to be in https://github.com/websocket-client/websocket-client/blob/master/websocket/_socket.py#L84 .

When the timeout is not zero, the `_recv` function is used to read from the socket. The problem is that inside that function `websocket-client` first tries to recv from the socket: `return sock.recv(bufsize)`  which has no timeout AFAIK and then tries to read from the socket using `select` https://github.com/websocket-client/websocket-client/blob/master/websocket/_socket.py#L94 which does implement the timeout.

There are other code sections which don't seem to be safe, for example https://github.com/websocket-client/websocket-client/blob/master/websocket/_abnf.py#L387 has two problems:

 * The timeout specified by the caller, let's say 1 second, is implemented inside https://github.com/websocket-client/websocket-client/blob/master/websocket/_abnf.py#L396 , but that line is called multiple times in a loop. So the effective timeout might be different from the specified timeout.
 * The `while shortage > 0:` might potentially lead to an endless loop

I've been working on fixes for these issues but was unable to complete them in the time I had for my project. Hopefully I'll be able to complete them in the near future.

Also, before sending a PR I would like to get @liris' input on this issue and the source code lines I'm referencing.

**Comment by matseymour28590** [comment] 2020-03-18 10:40
> The issue seems to be in https://github.com/websocket-client/websocket-client/blob/master/websocket/_socket.py#L84 .
> 
> When the timeout is not zero, the `_recv` function is used to read from the socket. The problem is that inside that function `websocket-client` first tries to recv from the socket: `return sock.recv(bufsize)` which has no timeout AFAIK and then tries to read from the socket using `select` https://github.com/websocket-client/websocket-client/blob/master/websocket/_socket.py#L94 which does implement the timeout.
> 
> There are other code sections which don't seem to be safe, for example https://github.com/websocket-client/websocket-client/blob/master/websocket/_abnf.py#L387 has two problems:
> 
>     * The timeout specified by the caller, let's say 1 second, is implemented inside https://github.com/websocket-client/websocket-client/blob/master/websocket/_abnf.py#L396 , but that line is called multiple times in a loop. So the effective timeout might be different from the specified timeout.
> 
>     * The `while shortage > 0:` might potentially lead to an endless loop
> 
> 
> I've been working on fixes for these issues but was unable to complete them in the time I had for my project. Hopefully I'll be able to complete them in the near future.
> 
> Also, before sending a PR I would like to get @liris' input on this issue and the source code lines I'm referencing.

Hi @andresriancho i'm assuming you never got round to submitting that pull request since this issue is still open... it would be very useful to my team if these issues were resolved so maybe we could collaborate on finishing the fixes if you're busy.

**Comment by VeNoMouS** [comment] 2020-05-25 04:43
Yea, i too am wondering if there is a resolve for this?!

**Comment by engn33r** [comment] 2021-04-30 01:47
This is a commonly encountered question, but I am wondering if someone has found a custom workaround for this? I suspect there are multiple ways this can be handled in a user's custom code.

For a long-term solution for websocket-client, I think it would be worth investigating whether a recv() function timeout parameter could be created (maybe this effectively identical to `setdefaulttimeout()`) and whether a thread-based solution could simplify things. The [threading documentation](https://websocket-client.readthedocs.io/en/latest/threading.html) for this project is in need of help, so if you have ideas or examples to contribute, please share.

Sorry for the delay on this topic, but I will plan to respond to the earlier feedback in this thread in the next 3-4 weeks when I have some hours to study this deeply enough.

**Comment by engn33r** [comment] 2021-06-04 01:30
If @digdig is correct in suggesting a `ws.recv()` lock may be causing this, then using `enable_multithread=True` should help here. As of commit beb135a, `enable_multithread=True` is the default, whereas the default value was `False` previously.

@andresriancho suggested other root causes related to timeouts that I haven't examined in depth.

What I will do is close this issue for now, but if someone reports the same issue reoccurred with the latest websocket-client version, we can troubleshoot this in more detail when we have some sample code and other info from the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md) to help analyze this issue. Right now I don't have a way to replicate this issue, so I can only speculate what the issue was.

**Closed by engn33r** 2021-06-04 01:30 UTC
