### ISSUE TITLE
SSL OSError: [Errno 14] Bad address error seen on using websocket-client 

### ISSUE THREAD

**Issue by RajarathinamC** [websocket-client/websocket-client#693] opened 2021-05-13 10:36 UTC
Hi,

I am using websocket-client module purely from client perspective to connect to a websocket server. 

Here is the environment detail

OS:  Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-129-generic x86_64)
Python 3.7.7
OpenSSL 1.1.0g  2 Nov 2017
Websocket version 0.58.0

We are getting following error very often from the client side while sending the data in the established websocket connection. 

    ws_obj.send(json.dumps(api_request))
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 282, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 310, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 510, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 168, in send
    return _send()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 150, in _send
    return sock.send(data)
  File "/usr/local/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
OSError: [Errno 14] Bad address

Could someone please help on how to solve it?

**Comment by engn33r** [comment] 2021-05-13 14:59
Can you provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so I can try to recreate this error? And does this error happen every time that a message is sent, or only sometimes?

You should try running your code on a newer system with a more updated OpenSSL version. This was the fix in issue #149, which gave the same error.

**Comment by RajarathinamC** [comment] 2021-05-14 09:23
Thanks @engn33r  for the response. Below is what we are trying to do to connect to the WSS. It is not always. It happens once in 5 attempts atleast and happens randomly. I had checked #149 . The server where we are running into this issue is having open ssl version higher than the problematic one mentioned in the issue #149. 
Are you suggesting to upgrade this open SSL to the latest one and observe ?. 

will changing it to use TLS solve it instead of the default SSL V2/V3?. 

Please let me know. 


def send_unsolicited_pong(ws_obj):
    if ws_obj:
        while ws_obj.connected:
            ws_obj.pong("0xA")
            time.sleep(5)

def get_websocket_connection(wss_url,access_token):

    ws_initial = create_connection(wss_url, sslopt={"cert_reqs": ssl.CERT_NONE},
                                   header={'sec-websocket-protocol': access_token,
                                           'User-Agent': 'Automation_Client'})
    ws_initial.recv()
    thread_pool = ThreadPool(processes=1)
    thread_pool.apply_async(send_unsolicited_pong, args=(ws_initial,), )
    return ws_initial

**Comment by engn33r** [comment] 2021-05-14 14:06
> Are you suggesting to upgrade this open SSL to the latest one and observe ?.

Yes, install a newer version of OpenSSL on your system and see if the issue is solved.

It looks like you are using async threads. I do not know if this might contribute to the issue because I am not an expert in thread management, but from what I have gathered from past issues, this library works better with synchronous threads instead of async. Maybe the [project documentation on this topic](https://websocket-client.readthedocs.io/en/latest/threading.html) will help.

**Comment by engn33r** [comment] 2021-05-22 01:21
Closing with the assumption that this is an OpenSSL issue and not a websocket-client issue.

**Closed by engn33r** 2021-05-22 01:21 UTC

**Comment by RajarathinamC** [comment] 2021-06-02 11:07
Hi @engn33r ,

I installed Open SSL to the latest openssl-1.1.1k version. Now we don't see the bad address problem. I have also pointed Web socket client to user TLS1.2. Code is exactly same as above but we just added  " "ssl_version":ssl.PROTOCOL_TLSv1_2". 
Now we started getting SSL EOF errors intermittently. Any pointers to solve it?

  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 283, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 311, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 515, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 175, in send
    return _send()
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 152, in _send
    return sock.send(data)
  File "/usr/local/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2408)

**Comment by engn33r** [comment] 2021-06-02 12:24
This still looks like an openssl issue to me and not a websocket-client issue. I would suggest googling "python ssl.SSLEOFError" and following the advice there, because I am not an expert with openssl errors.

**Comment by RajarathinamC** [comment] 2021-06-03 07:06
ok.sure. thanks.
