### ISSUE TITLE
WebSocket tries to connect via IPV6 if the local device has an IPV6 IP, but there's not ISP IPV6 service.

### ISSUE THREAD

**Issue by QuinnDamerell** [websocket-client/websocket-client#775] opened 2021-12-30 15:53 UTC
Hello! 

I use this library in a plugin that's used by thousands of home ISP-based users. My users use both PY 2.7 and PY 3. I enabled IPV6 on my service recently and some of my users started having trouble connecting. After debugging with a few users, I noticed a common theme. If the user's router is assigned an IPV6 address the websocket will always try to connect via IPV6, even if there is no internet connection available. I was able to confirm that via a traceroute, where I can see the correct path of the IPV4 address but the path for the IPV6 address ends after just one hop to the router. The users have also confirmed that their ISP doesn't give them an IPV6 address.

For reference, other PY libs, like the requests lib, are handling the setup correctly and I assume fall back to IPV4.

**Comment by engn33r** [comment] 2021-12-30 16:32
This looks like a duplicate of #522. The users should still get a connection, even if it is a bit delayed, based on what was reported in #773.

Are you able to provide any error traces to assist with debugging this? Is there a public websocket endpoint using IPv6 that you are using? I have not been able to recreate the few IPv6 errors reported with this library in the past.

**Comment by QuinnDamerell** [comment] 2021-12-30 17:00
Thanks for the info! I can try to get info from my users, but it's hard. 

What I'm seeing is the connection fails with "Network unreachable". I can say for sure the user's router is giving the device both an IPV4 and IPV6 address, but there's no route to the internet past the local router for IPV6. 

Feel free to use my websocket server for testing, `wss://starport-v1.octoeverywhere.com`. You won't be able to use the protocol, but you can at least connect to it.

**Comment by engn33r** [comment] 2021-12-30 22:02
Ok good to know you're seeing the same "Network unreachable" error as reported in #522. I just pushed commit da1b050 based on the solution mentioned in #522 which might help based on the information you shared. It would be great if you're able to get feedback whether this modification helps. If it is easier for you to get feedback after a new websocket-client release, I can release 1.2.4 soon.

**Comment by engn33r** [comment] 2022-02-07 01:09
I will close this for now because commit da1b050 might help, but if this IPv6 issue appears again in the future, I can take a closer look.

**Closed by engn33r** 2022-02-07 01:09 UTC
