### ISSUE TITLE
Digest Auth

### ISSUE THREAD

**Issue by dalykevin** [websocket-client/websocket-client#331] opened 2017-06-30 15:33 UTC
Noticed a TODO in the source code to add DIgest Auth support for Proxy Access. Any immediate plans to add this feature.

Any suggestion on how this could be done.

**Comment by engn33r** [comment] 2021-02-08 04:55
Issue #470 has more details on this same topic, so I will close this issue out as a duplicate of 470, even though this issue was created first. Unfortunately digest auth support is not a top priority for this project to implement at the current time, but PRs are welcome! And project priorities may change over time.

**Closed by engn33r** 2021-02-08 04:55 UTC
