### ISSUE TITLE
The module name in setup.py should be "websocket-client"

### ISSUE THREAD

**Issue by qlan2** [websocket-client/websocket-client#482] opened 2018-09-19 16:39 UTC
Hey guys,

It seems the module name in your setup.py file is "websocket_client", which is not the same as the official name "websocket-client". 

https://pypi.org/project/websocket-client/#files     "websocket_client-0.53.0.tar.gz" -> "websocket-client-0.53.0.tar.gz"
https://pypi.org/project/google-auth/#files            "google-auth-1.5.1.tar.gz"

**Comment by hacky97** [comment] 2018-12-31 00:16
it is also confusing to see the code using "import websocket" and the actual package name being websocket-client, or is it just me?

**Comment by engn33r** [comment] 2021-01-28 03:44
I agree that there are some name mismatches. As best as I can tell, the setup.py name changed from websocket-client to websocket_client with commit c616e43 due to issue #147. As for using "import websocket", I think this is a duplicate of issue #60 and I would refer further suggestions on this topic to the older pre-existing issue.

I would welcome input on how the setup.py name could be changed without recreating issue #147 since I'm not an expert on PyPI.

**Closed** 2021-03-04 04:21 UTC
