### ISSUE TITLE
Segmentation fault after websocket.close()

### ISSUE THREAD

**Issue by safrimus** [websocket-client/websocket-client#599] opened 2020-01-24 21:29 UTC
```
Fatal Python error: Segmentation fault

Current thread 0x00007fe75b7c6700 (most recent call first):
File "/usr/lib/python2.7/ssl.py", line 725 in send
File "/usr/local/lib/python2.7/dist-packages/websocket/_socket.py", line 139 in _send
File "/usr/local/lib/python2.7/dist-packages/websocket/_socket.py", line 157 in send
File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 448 in _send
File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 278 in send_frame
File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 253 in send
File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 304 in pong
File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 361 in recv_data_frame
File "/usr/local/lib/python2.7/dist-packages/websocket/_app.py", line 271 in read
File "/usr/local/lib/python2.7/dist-packages/websocket/_app.py", line 66 in read
File "/usr/local/lib/python2.7/dist-packages/websocket/_app.py", line 305 in run_forever
File "/usr/lib/python2.7/threading.py", line 754 in run
File "/usr/lib/python2.7/threading.py", line 801 in __bootstrap_inner
File "/usr/lib/python2.7/threading.py", line 774 in __bootstrap
```

Immediately prior to this crash, the websocket send() raises a `socket.error` exception with this message : `EOF occurred in violation of protocol (_ssl.c:1829)`. I have a try-catch for this exception and in the handler, I `close()` the websocket.

It looks like the client is trying to respond to a ping from the server at the same time as the websocket disconnection. But unfortunately I haven't yet figured out how to reproduce the fault. I was hoping someone more familiar with this library is able to help with debugging this further.

**Comment by engn33r** [comment] 2021-02-15 04:07
I'm going to close this issue now because it does not appear to be repeatable, but if you do find a way to recreate the issue, please share and reopen the issue. Based on the last few lines of the error you provided, it looks like a threading issue may exist, which might explain why recreating the issue is hard. The [project documentation](https://websocket-client.readthedocs.io/en/latest/threading.html) has a threading page since this is a known problem point, but the threading documentation needs more information added (at the time of writing).

**Closed by engn33r** 2021-02-15 04:07 UTC
