### ISSUE TITLE
Can't get problem details when got WebSocketException at handshake

### ISSUE THREAD

**Issue by murata100** [websocket-client/websocket-client#606] opened 2020-03-05 05:57 UTC
some services returns problem details when handshake.
[RFC7807 Problem Details for HTTP APIs](https://tools.ietf.org/html/rfc7807)

but client don't read body.
only headers.

`handshake_response` is not set (None).

**Comment by engn33r** [comment] 2021-02-07 06:14
Sorry, I don't understand your question. Can you either provide the code you are using or provide the verbose logging details using the [enableTrace(True) function](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options)? I am guessing that you are encountering a scenario where the server returns an error message after the handshake request, and this means that there is either a problem with the server or the way you have customized your connection request. You can try using the new [project examples](https://websocket-client.readthedocs.io/en/latest/examples.html#) to see if they help with your issue. I am closing this issue for now, but if the issue is not resolved and you have additional details to add, you can reopen the issue.

**Closed by engn33r** 2021-02-07 06:14 UTC
