### ISSUE TITLE
How to get Reason for OnClose()

### ISSUE THREAD

**Issue by srini-murthy** [websocket-client/websocket-client#355] opened 2017-09-19 17:24 UTC
When Server Closes WebSocket connection - I receive OnClose() Event - How to get reason in Onclose event - What parameter I need to use to get Reason for close 
Thanks in advance 
Srini

**Comment by utdrmac** [comment] 2017-10-09 16:52
*bump* close_args are collected but not passed to the callback. https://github.com/websocket-client/websocket-client/blob/d97eadb070d685aac207fcf6d663a013db42d86a/websocket/_app.py#L242

My code:
```
class wsTicker:
...
    def on_close(self, ws, args):
          logging.error("Websocket closed! {}".format(args))
```

error:
```
2017-10-09 11:46:14,997 - ERROR - error from callback 
<bound method wsTicker.on_close of <__main__.wsTicker 
object at 0x11251e210>>: on_close() takes exactly 3 arguments (4 given)
```

**Comment by skeller88** [comment] 2020-01-22 23:55
bump

**Comment by engn33r** [comment] 2021-03-05 01:47
This looks like a duplicate of #558, and I think PR #265 helped enable this feature. [This new documentation section](https://websocket-client.readthedocs.io/en/latest/examples.html#connection-close-status-codes) should answer the question above. If not, please elaborate on this documentation section doesn't cover and I can reopen the issue.

**Closed by engn33r** 2021-03-05 01:47 UTC
