### ISSUE TITLE
With 0.58.0 version, change in WebSocketApp callback(self, callback, *args) causes disruption with on_messsage class method

### ISSUE THREAD

**Issue by PFaurel** [websocket-client/websocket-client#669] opened 2021-03-11 07:59 UTC
Could you explain why did you reverted the app.py code to V48 version ?

    def _callback(self, callback, *args):
        if callback:
            try:
                if inspect.ismethod(callback):
                    callback(*args)
                else:
                    callback(self, *args)
was reverted to:

    def _callback(self, callback, *args):
        if callback:
            try:
                callback(self, *args)

That's a major change and cause disruption with any WebSocketApp client that set on_message to a class method => signature needs to be changed ! 
With 0.57.0 => self._callback(self.on_message, data) => on_message(data)
With 0.58.0 => self._callback(self.on_message, data) => on_message(websocketapp, data)

**Comment by BobDG** [comment] 2021-03-11 11:10
Thanks for posting this! I saw that somehow my code didn't work at all but I couldn't find the change that caused it.
This breaks ALL on_ methods, on_error, on_message, on_close, on_open.. It's a huge change and breaks all code.
For people looking to fix this in their code, simply add _ or 'ws' or whatever if you actually want to use it to all these methods:

`    
    def on_message(self, _, message):
        print(f'Got message: {message}')

    def on_ping(self, _):
        print(f'Pinged!')

    def on_pong(self, _):
        print(f'Ponged!')

    def on_error(self, _, error):
        print(f'Error in websocket: {error}')

    def on_close(self, _):
        print("Websocket closed!")

    def on_open(self, _):
        print('Connected to Websocket')
`

**Comment by PFaurel** [comment] 2021-03-11 11:38
Thank you for your quick response.
Do you plan to keep this or revert in a next version ?

**Comment by BobDG** [comment] 2021-03-11 13:19
I'm not the creator of this framework unfortunately, I'm just a user with the same issue as you ;)

**Comment by elderlabs** [comment] 2021-03-12 05:07
To add my two cents in here, I'm not experiencing this issue on my end. I'm using this with a project named Disco, for use with Discord. I have noticed `on_error` doesn't seem to fire correctly, perhaps. Adding `_` to my calls does break things, though, so I wonder if there's something I'm doing on my end that's not being done in your projects.

**Comment by BobDG** [comment] 2021-03-12 07:41
@elderlabs Hm you sure you're using the latest 0.58 version? If so, perhaps it's got something to do with how you setup the callbacks. I do it like so:
`self.ws = websocket.WebSocketApp(
            url=f'wss://stream.blabla',
            on_message=self.on_message,
            on_error=self.on_error,
            on_close=self.on_close,
            on_open=self.on_open
        )`

**Comment by engn33r** [comment] 2021-03-12 20:30
Hi everyone, this is a duplicate of the last 2 issues created, #668 and #667. For the history on the change that is causing this issue, see commit 3112b7d. As noted in #667, I should probably release a 1.0.0 release shortly for proper semver. I am open to reintroducing inheritance that PR #442 originally introduced, but that particular PR caused many other issues, which is why it was reverted. You will probably need to use release 0.57.0 if you do not want to modify your code.

I will keep this issue open until the new release is created (and possibly after) in hopes that others having the same issue see this rather than creating a new issue.

@elderlabs FYI it's possible that what you're seeing might be a different issue (possibly related to #612), but I'm not certain

**Comment by engn33r** [comment] 2021-05-18 02:12
Version 1.0.0 is now released and it follows proper semantic versioning to indicate a potentially breaking change. This issue is referenced in the release notes for v1.0.0 so anyone who upgrades to 1.0.0 and observes problems might have an easier time finding this issue. Version 1.0.0 includes the additional change of removing Python 2 support. I will close this issue because I think I have documented this change as best as I can at the current time.

**Closed by engn33r** 2021-05-18 02:12 UTC

**Comment by nyuszika7h** [comment] 2021-07-16 10:06
I know this is already resolved, but technically you were not wrong to make a breaking change, in 0.x.y anything may change at any time (though it's good practice to at least avoid breaking changes in patch releases like 0.57.1 - this is just a hypothetical example, that release didn't actually exist).
