### ISSUE TITLE
If ssl is not available, an exception is raised

### ISSUE THREAD

**Issue by jorgelscati** [websocket-client/websocket-client#610] opened 2020-03-24 13:44 UTC
If ssl module is not available, this exception is raised:

'function' object has no attribute 'SSLSocket'
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\websocket\_app.py", line 257, in run_forever
    dispatcher = self.create_dispatcher(ping_timeout)
  File "C:\Python27\lib\site-packages\websocket\_app.py", line 317, in create_dispatcher
    if self.sock.is_ssl():
  File "C:\Python27\lib\site-packages\websocket\_core.py", line 182, in is_ssl
    return isinstance(self.sock, ssl.SSLSocket)
AttributeError: 'function' object has no attribute 'SSLSocket'

When ssl module is not available, in _ssl_compat.py file, ImportError es captured and "ssl = lambda: None"

When "sock" is checking if it is a "ssl" instance, it checks "isinstance(self.sock, ssl.SSLSocket)". 

But ssl is equal to None, so it is impossible that this module has a SSLSocket class.

I am using Python 2.7

**Comment by engn33r** [comment] 2021-02-23 03:51
Sorry, I am a little confused about what the issue is here. The _ssl_compat.py file does have a try-catch statement that will result in an ImportError if you do not have ssl. It is recommended to install ssl, but at the moment it is not listed as a dependency. Are you suggesting that ssl should be a dependency of this project? Or are you suggesting that the `ssl = lambda: None` line in the _ssl_compat.py file should be changed? I would like to point out that there is a dependency of backports.ssl_match_hostname for Python 2.x, which appears to be what you are using. Does the error still occur when this dependency is installed?

I am also confused because you mentioned the code `isinstance(self.sock, ssl.SSLSocket)` from the is_ssl() function in _core.py. This function returns a boolean value, so it can be True or False, depending on which situation is encountered. Can you add more details around what you think is wrong with this function?

I will close this issue for now, since I am guessing you have resolved the issue by now, but I am very happy to reopen the issue if you think a specific change should be made in this library to better handle the situation where ssl is not available.

**Closed by engn33r** 2021-02-23 03:51 UTC

**Comment by engn33r** [comment] 2021-02-23 04:28
Additional note for reference: this might be related to issue #532
