### ISSUE TITLE
websocket should default to enable_multithread=True

### ISSUE THREAD

**Issue by scottbecker** [websocket-client/websocket-client#591] opened 2019-12-05 15:14 UTC
Why not always be thread safe? The following issue was a real head scratcher until we realized that this library has to be told that you are using threads.

-------------------------

We are seeing the following error occasionally.  It happens on multiple connections to the same server at the same time making me think this is actually a snapped connection in disguise.  Is this something that the websocket client can catch and raise as a more obvious error?

```
2019-12-05 13:06:10,413 [ERROR] root: [SSL: BAD_LENGTH] bad length (_ssl.c:2341)
Traceback (most recent call last):
  File "<our code>", line 268, in _check_for_connection_alive
    self.send_ws_ping()
  File "<our code>", line 226, in send_ws_ping
    self.ws.ping("keepalive")
  File "/home/ubuntu/venv3.7/lib/python3.7/site-packages/websocket/_core.py", line 294, in ping
    self.send(payload, ABNF.OPCODE_PING)
  File "/home/ubuntu/venv3.7/lib/python3.7/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/home/ubuntu/venv3.7/lib/python3.7/site-packages/websocket/_core.py", line 278, in send_frame
    l = self._send(data)
  File "/home/ubuntu/venv3.7/lib/python3.7/site-packages/websocket/_core.py", line 448, in _send
    return send(self.sock, data)
  File "/home/ubuntu/venv3.7/lib/python3.7/site-packages/websocket/_socket.py", line 151, in send
    return _send()
  File "/home/ubuntu/venv3.7/lib/python3.7/site-packages/websocket/_socket.py", line 136, in _send
    return sock.send(data)
  File "/usr/lib/python3.7/ssl.py", line 984, in send
    return self._sslobj.write(data)
ssl.SSLError: [SSL: BAD_LENGTH] bad length (_ssl.c:2341)
```

**Comment by Odianosen25** [comment] 2019-12-14 07:10
Having the same issue, but please @scottbecker, what is the best way to handle it if I may ask? My code though resets the connection to the server, but it’s so not ideal. Have you any idea why such happens outside a network issue? As I have my server running in the cloud and don’t understand why this happens all of a sudden. Though I seem to have it more, during the process of sending data.

**Comment by scottbecker** [comment] 2019-12-14 12:18
Right now I am doing what you are doing, just restarting the connection.

I suspect that this is actually a bug in openssl itself and there are some fixes that refer to issues that could cause our problem.  e.g. this one https://github.com/openssl/openssl/pull/8773

I was on:
OpenSSL 1.1.1a  20 Nov 2018

I just updated to 1.1.1d.  I'll report back in a few days if I am seeing the issue still


Here is how I updated ssl

```
cd ~/
wget https://www.openssl.org/source/openssl-1.1.1d.tar.gz --no-check-certificate
tar xvf openssl-1.1.1d.tar.gz
cd openssl-1.1.1d/
sudo ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
sudo make
sudo make install
```


Here is how to check what version of openssl you have and python is pointing to (before and after upgrade)


```
openssl version

python
import ssl
ssl.OPENSSL_VERSION
```

**Comment by Odianosen25** [comment] 2019-12-14 13:12
Many thanks @scottbecker for the response.

I have just checked mine, and it is actually on `OpenSSL 1.1.1d  10 Sep 2019`. 

But kindly to let me know if it makes any help in your case, then maybe I could see if mine is based on something else.

Kind regards

**Comment by Odianosen25** [comment] 2019-12-18 07:49
Hello @scottbecker,

I think I might have gotten to the bottom of this, and just in case you have not I wanted to share my seemingly solution.

I made 3 changes to my client, and they are below:
- I specified `ENV WEBSOCKET_CLIENT_CA_BUNDLE /etc/ssl/certs` in my docker image
- Initially I was using only certificate and not keys,  and added these
- But lastly, what I think really solved it was I noticed in the source code, by default it was using SSLv23 [here](https://github.com/websocket-client/websocket-client/blob/master/websocket/_http.py#L207). So I passed `ssl.PROTOCOL_TLS` as `ssl_version` in sslopt. I understand the former is an alias for the later, but since its said its been depreciated, not sure it means anything

Since I did the above, I haven't had that issue for at least 24 hours, even when sending heavy base64 based data. Might be an early "victory" dance, but felt I should share it, and maybe you could give better insight as I am not really an experienced programmer myself, but a hobbyist.

Kind regards

**Comment by Odianosen25** [comment] 2019-12-21 21:53
Ok I think I finally nailed it now as with the above, I was still getting the error. So after digging a bit more, I just enabled multi-threading by using `enable_multithread=True`. This enables the locking mechanism within the client, and I think its now stable.

**Comment by scottbecker** [comment] 2019-12-22 22:50
@Odianosen25 sounds promising (we use a lot of threads).  I will give this a try.

**Comment by Odianosen25** [comment] 2019-12-23 07:00
Hello @scottbecker, yeah but in my case, as I am working in an async environment, that didn’t also completely solve it, since it was being called within an executor thread. So still kind of isolated, from when another executor thread calls again when one running already. So I ended up using `asyncio.Lock()` by using the `async with lock:` context before calling any executor. 

This completely solved my issue, as even though I am sending video over the internet, it’s now quite stable and wasn’t breaking again.

Hope this helps

**Comment by scottbecker** [comment] 2019-12-24 20:52
Too late now but wouldn't the "websockets" library be better out of the gate in an async environment? (since its build on asyncio?)

https://websockets.readthedocs.io/en/stable/intro.html#installation

**Comment by Odianosen25** [comment] 2019-12-24 21:09
No this client is not built on asyncio, as it says it in the description, `All APIs are the synchronous functions.`. The link you sent, is to another wesocket client.

But this works great for me so far, as the other has more than I need, and so not needed for me.

**Comment by engn33r** [comment] 2021-06-04 01:23
I don't see any downsides to setting `enable_multithread=True` by default, but we'll see if I overlooked something. Commit beb135a fixes this. Duplicate of #507.

**Closed by engn33r** 2021-06-04 01:23 UTC

**Comment by hhuuson97** [comment] 2025-05-06 07:17
There're a lot of downsides.
When I implemented with trading view, I figure out that this error was coming from my code cannot process fast enough to response ping/pong message. As a result, trading view server closed connection and websocket-client returned error when I send messages to response after that.
`enable_multithread=True` isn't a good practice. It's slow down a lot, because of thread-lock.
