### ISSUE TITLE
Suggestion on changing import name

### ISSUE THREAD

**Issue by zz090923610** [websocket-client/websocket-client#313] opened 2017-04-05 19:59 UTC
This package is really good, however when integrating it using PyCharm, on line:

`import websocket`

PyCharm would suggest "Add requirement 'websocket' to requirements.txt", however that is another package. In fact we should add 'websocket-client' to  requirements.txt.
I think this would lead to some kind of problem, not a big deal, but rather annoying and unable to fix if without cautions.

**Comment by engn33r** [comment] 2021-02-07 05:39
This looks like a duplicate of #60, so I'll close this out for now

**Closed by engn33r** 2021-02-07 05:39 UTC
