### ISSUE TITLE
Websocket-client: How to reconnect to lost closed connection.

### ISSUE THREAD

**Issue by ChristianBEng** [websocket-client/websocket-client#678] opened 2021-04-20 14:16 UTC
I am actually trying to run the websocket-client with Python 3.9.2 in PyCharm IDE. But i never get it over a few hours without getting disconnected. The problem is beyond my current knowledge and i want to solve it :-).
How can i automatically reconnect? Or why do i get disconnected? 

I was testing the Websocket without any usage of the incoming data, just to get sure there is no Problem with my Code.

You can find the Doc´s for the websocket from binance [here](https://binance-docs.github.io/apidocs/futures/en/#websocket-market-streams).
The following Error is raised.
[WinError 10054] An existing connection was forcibly closed by the remote host.

```
import websocket
from datetime import datetime

websocket.enableTrace(True)
socketurl_combined = "wss://fstream.binance.com/stream?streams=btcusdt_perpetual@continuousKline_1m/btcusdt_perpetual@continuousKline_5m"


def on_message(wsapp, message):
    # print(message)
    pass [..... normaly Code is executed in this function....]


def on_open(wsapp):
    print(f'{str(datetime.now())}   ### ONLINE ###')


def on_close(wsapp):
    print(f'{str(datetime.now())}   ### OFFLINE ###')


def on_error(wsapp, error):
    print(f'{str(error)}   ### OFFLINE ###')


def on_ping(wsapp, message):
    print(f'{str(datetime.now())}   ### Got a Ping! ###')


def on_pong(wsapp, message):
    print(f'{str(datetime.now())}   ### Send a Pong! ###')


wsapp = websocket.WebSocketApp(socketurl_combined,
                               on_open=on_open,
                               on_message=on_message,
                               on_error=on_error,
                               on_close=on_close,
                               on_ping=on_ping,
                               on_pong=on_pong)


wsapp.run_forever(ping_interval=60, ping_timeout=30)
```

If it is helpfull, i can post the Tracelog.

For any advice i will be gratefull.

Thanks a lot!!

**Comment by alexnanzer** [comment] 2021-04-20 14:18
Maybe but not sure the remote host closes it himself as there is no traffic on it for a specific period

**Comment by ChristianBEng** [comment] 2021-04-20 14:28
Below you can see the Tracelog. With traffic you mean the send data from websocket?

How can i log the traffic to see if this raises the problem?

```
--- request header ---
GET /stream?streams=btcusdt_perpetual@continuousKline_1m/btcusdt_perpetual@continuousKline_5m HTTP/1.1
Upgrade: websocket
Host: fstream.binance.com
Origin: http://fstream.binance.com
Sec-WebSocket-Key: BN516w/kvd1qzL9e6u8aeA==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Date: Tue, 20 Apr 2021 09:59:02 GMT
Connection: upgrade
upgrade: websocket
sec-websocket-accept: o2uw4vJ6x4UUToB+QuCy83sutok=
-----------------------
2021-04-20 11:59:02.878379   ### ONLINE ###
send: b'\x89\x80\x99(Up'
2021-04-20 12:00:03.148047   ### Send a Pong! ###
2021-04-20 12:00:10.738260   ### Got a Ping! ###
send: b'\x8a\x80\xd7x\xc6\xac'
send: b'\x89\x80\x8d\x18\xda\x84'
2021-04-20 12:01:03.204958   ### Send a Pong! ###
send: b'\x89\x80\x07\xad-\xec'
2021-04-20 12:02:03.175428   ### Send a Pong! ###
send: b'\x89\x80?=\x0c\xbc'
2021-04-20 12:03:03.228924   ### Send a Pong! ###
send: b'\x89\x80 \n\x06N'
2021-04-20 12:04:03.197726   ### Send a Pong! ###
send: b'\x89\x80\x99\xb2\xb8g'
2021-04-20 12:05:03.200123   ### Send a Pong! ###

[.......]

send: b'\x89\x80\x08\xb9qa'
2021-04-20 13:15:03.842624   ### Send a Pong! ###
2021-04-20 13:15:10.693830   ### Got a Ping! ###
send: b'\x8a\x80?-\xc6\x15'
send: b'\x89\x801\xf7Z\xdd'
2021-04-20 13:16:03.848965   ### Send a Pong! ###
send: b'\x89\x80\xea=\xaa\x83'
2021-04-20 13:17:03.854880   ### Send a Pong! ###
send: b'\x89\x80\x91\x98\x97\x96'
2021-04-20 13:18:03.854548   ### Send a Pong! ###
send: b'\x89\x80VM\xdf\xfa'
2021-04-20 13:19:03.855784   ### Send a Pong! ###
send: b'\x89\x80\x0c\x02\xbbC'
2021-04-20 13:20:03.859769   ### Send a Pong! ###
send: b'\x8a\x80%n\xab\x8b'
2021-04-20 13:20:10.693723   ### Got a Ping! ###
send: b'\x89\x80\xa5\r\xa0I'
2021-04-20 13:21:03.863609   ### Send a Pong! ###
send: b'\x89\x80\xc2\xb8\xb64'
2021-04-20 13:22:03.879861   ### Send a Pong! ###
send: b'\x89\x80\x01\x01\x0f\xc4'
send: b'\x88\x82V\x91\x99\xf3Uy'
[WinError 10054] An existing connection was forcibly closed by the remote host   ### OFFLINE ###
2021-04-20 13:23:25.304860   ### OFFLINE ###

Process finished with exit code 0
```

**Comment by engn33r** [comment] 2021-04-21 01:31
Thank you for providing a tracelog and details around your issue. I have some questions that might help provide you with proper feedback:
1. Are you using the latest websocket-client version 0.58.0?
2. Which version of Windows are you using?
3. Did you try googling "WinError 10054" to troubleshoot this Windows error? The problem might not be in websocket-client. For example, [this page from Microsoft](https://support.microsoft.com/en-us/topic/an-application-may-receive-the-10054-error-when-the-application-receives-data-from-a-connection-on-a-computer-that-is-running-windows-7-or-windows-server-2008-r2-if-a-tdi-filter-driver-is-installed-73fd74a9-51c2-3663-e965-e1187b1cfc92) has some suggestions.
4. Are you able to connect to the binance API from the same computer using another tool or someone else's code? Or is this the first time you are connecting to the binance API from this computer?

I have not seen this error before, but two past issues mention WinError 10042, #404 and #370. I do not know if Windows error 10042 is related to 10054.

**Comment by ChristianBEng** [comment] 2021-04-21 09:56
Thank you @engn33r taking part solving this issue.

1. Yes, i am using Websicket.-client 0.58.0 and six 1.15.0.
2. My OS is Windows 10 Home Version	10.0.19041 Build 19041
3. Yes i was searching first, and later i created this issue. Problem with googling the WinError is, that there are many suggestions and solutions, most of them i don´t understand, those i understand like firewall problems and old version i already checked.
4. I tried several times in the last weeks to connect to the websocket using websocket-client and the same url.
I build up this code "by my own". No copy paste by cmd +c; cmd+v,  i typed it by my self, if you think about this.
I tried binance-client with my API-Keys. That worked. But the binance-client with API-key i only use to get historical data once and not like websocket-client for infinite data.
I never used any other PC oder MAC to connect to binance. I would not say that it is the first time. I tried several times in the past days, ever got disconnected after 30min up to 17 hours longest.

Below you can see the binance-client i used once a few days ago, but its complete other data i used there.

```
from binance.client import Client
import config
from datetime import datetime



client = Client(config.API_KEY, config.SECRET_KEY)

with open("BTCUSDT_Spot_1_Minute_Kline_2020.txt", "a") as file:
    file.write(str("date") + "," +
               str("open") + "," +
               str("high") + "," +
               str("low") + "," +
               str("close") +
               "\n")


klines = client.get_historical_klines("BTCUSDT", Client.KLINE_INTERVAL_1MINUTE, "1 Jan, 2020")
for candles in klines:
    opentime = datetime.fromtimestamp(int((candles[0] * 0.001)))
    openprice = candles[1]
    highprice = candles[2]
    lowprice = candles[3]
    closeprice = candles[4]
    with open("BTCUSDT_Spot_1_Minute_Kline_2020.txt", "a") as file:
        file.write(str(opentime) + "," +
                   openprice + "," +
                   highprice + "," +
                   lowprice + "," +
                   closeprice +
                   "\n")
```

**Comment by ChristianBEng** [comment] 2021-04-21 13:44
@engn33r
I started  Tue, 20 Apr 2021 20:22:40 GMT another try with the almost identical code as in my first post in this issue. I used a small change and added the run_forever() below my on_exit() function. So the run_forever() statement was two times in my code and the ping_interval was 30sec.

```
import websocket
from datetime import datetime

websocket.enableTrace(True)
socketurl_combined = "wss://fstream.binance.com/stream?streams=btcusdt_perpetual@continuousKline_1m/btcusdt_perpetual@continuousKline_5m"


def on_message(wsapp, message):
   # print(message)
    pass


def on_open(wsapp):
    print(f'{str(datetime.now())}   ### ONLINE ###')


def on_close(wsapp):
    print(f'{str(datetime.now())}   ### OFFLINE ###')


def on_error(wsapp, error):
    print(f'{str(error)}   ### ERROR ###')
    print(f'{str(datetime.now())}')
    wsapp.run_forever(ping_interval=30, ping_timeout=20)


def on_ping(wsapp, message):
    print(f'{str(datetime.now())}   ### Got a Ping! ###')


def on_pong(wsapp, message):
    print(f'{str(datetime.now())}   ### Send a Pong! ###')


wsapp = websocket.WebSocketApp(socketurl_combined,
                               on_open=on_open,
                               on_message=on_message,
                               on_error=on_error,
                               on_close=on_close,
                               on_ping=on_ping,
                               on_pong=on_pong)


wsapp.run_forever(ping_interval=30, ping_timeout=20)
```

it raised the same error.

```
--- request header ---
GET /stream?streams=btcusdt_perpetual@continuousKline_1m/btcusdt_perpetual@continuousKline_5m HTTP/1.1
Upgrade: websocket
Host: fstream.binance.com
Origin: http://fstream.binance.com
Sec-WebSocket-Key: jx0YUX22HNDmD21tPmRb2w==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Date: Tue, 20 Apr 2021 20:22:40 GMT
Connection: upgrade
upgrade: websocket
sec-websocket-accept: Mc3ioX5p3gYclhUuClsCSMJGJzk=
-----------------------
2021-04-20 22:22:39.976266   ### ONLINE ###
```
```
2021-04-21 14:54:19.705335   ### Got a Ping! ###
send: b'\x8a\x80\xb2\xbd\x89\xa0'
send: b'\x89\x80@ \xfe\x96'
2021-04-21 14:54:25.566543   ### Send a Pong! ###
send: b'\x89\x80BD\x19O'
2021-04-21 14:54:55.569799   ### Send a Pong! ###
send: b'\x89\x80\xcb\xe9\xa5\xe7'
2021-04-21 14:55:25.603960   ### Send a Pong! ###
send: b'\x89\x80\xef\xa0,C'
2021-04-21 14:55:55.635107   ### Send a Pong! ###
send: b'\x89\x80\xbb&\xf4*'
2021-04-21 14:56:25.649298   ### Send a Pong! ###
send: b'\x89\x80\xe6?\n\xc2'
2021-04-21 14:56:55.678567   ### Send a Pong! ###
send: b'\x89\x80\xd1(\xfa\xf8'
2021-04-21 14:57:25.622526   ### Send a Pong! ###
send: b'\x89\x80SY^\xb5'
error from callback <function on_error at 0x000001C8898775E0>: socket is already opened
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_app.py", line 388, in _callback
    callback(self, *args)
  File "E:\4_Dokumente\#50_Python\CryptoTradingBot\binance\Backtest.py", line 24, in on_error
    wsapp.run_forever(ping_interval=30, ping_timeout=20)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_app.py", line 261, in run_forever
    raise WebSocketException("socket is already opened")
send: b'\x88\x82Z\x8e\xe8wYf'
[WinError 10054] An existing connection was forcibly closed by the remote host   ### ERROR ###
2021-04-21 14:58:23.647059
2021-04-21 14:58:23.663488   ### OFFLINE ###

Process finished with exit code 0
```

**Comment by engn33r** [comment] 2021-04-26 15:35
I was unable to recreate the issue when I tested your code on both Linux and Windows 10. I ran the code for well over 12 hours with no connection problems. I used the first example you provided, with `wsapp.run_forever(ping_interval=60, ping_timeout=30)`, because `run_forever()` is only needed once. Because this issue does not repeat with the same runtime each time, I think the problem may be with your network or your device.

The first code example you shared is better than the most recent one, because placing `wsapp.run_forever()` in the `on_error` function is the cause of the most recent error you shared, as indicated by the lines:
```
  File "E:\4_Dokumente\#50_Python\CryptoTradingBot\binance\Backtest.py", line 24, in on_error
    wsapp.run_forever(ping_interval=30, ping_timeout=20)
```
You should only use run_forever() once.

I am going to close this issue for now but we can continue the conversation to try and replicate your issue if you have more ideas on how to do this. I have not seen other issues with this same error message, which makes me think that the problem is specific to your setup.

**Closed by engn33r** 2021-04-26 15:35 UTC

**Comment by ChristianBEng** [comment] 2021-04-26 16:18
Maybe the problem will come up, later. I was able to run the code in the last days on my MAC and PC. Normaly the problem raised after more then 10 hours.

But finaly after trying several solutions, the following worked. The code is running without stopping for nearly 48 hours on my MAC and on my PC in the same network. I think it is no network problem. I think it was the 24h disconnect from binance websocket-server (see the [documentation](https://binance-docs.github.io/apidocs/futures/en/#websocket-market-streams)). The last trys I only got "ping/pong timed out" Error, no WinError anymore (i only got it once).

```
import websocket
from datetime import datetime

websocket.enableTrace(True)
socketurl_combined = "wss://fstream.binance.com/stream?streams=btcusdt_perpetual@continuousKline_1m/btcusdt_perpetual@continuousKline_5m"


def on_message(wsapp, message):
    print(message)
    pass


def on_open(wsapp):
    print(f'{str(datetime.now())}   ### ONLINE ###')


def on_close(wsapp):
    print(f'{str(datetime.now())}   ### OFFLINE ###')


def on_error(wsapp, error):
    print(f'{str(error)}   ### OFFLINE ###')


def on_ping(wsapp, message):
    print(f'{str(datetime.now())}   ### Got a Ping! ###')


def on_pong(wsapp, message):
    print(f'{str(datetime.now())}   ### Send a Pong! ###')


wsapp = websocket.WebSocketApp(socketurl_combined,
                               on_open=on_open,
                               on_message=on_message,
                               on_error=on_error,
                               on_close=on_close,
                               on_ping=on_ping,
                               on_pong=on_pong)

wsapp.last_ping_tm = 32
wsapp.last_pong_tm = 1
while True:
    try:
        # ws.last_ping_tm = 0
        # ws.last_pong_tm = 0
        wsapp.run_forever(ping_interval=40, ping_timeout=30)
    except Exception as e:
        pass
```

**Comment by engn33r** [comment] 2021-04-27 01:50
Good, I am glad the WinError problem is not appearing again. The message `ping/pong timeout error` is printed from [this line](https://github.com/websocket-client/websocket-client/blob/719fc9d2e50e16292b4f09ca86385540456a55a7/websocket/_app.py#L346), so one of the variables `has_pong_not_arrived_after_last_ping` or `has_pong_arrived_too_late` must be true to reach this exception. I explained [in this long detailed comment](https://github.com/websocket-client/websocket-client/pull/611#issuecomment-786395942) how the current checks around ping timeout are quite simple and leave room for possible improvement. My best guess is that a network delay somewhere between you and the binance server causes one pong packet to arrive late, triggering the error.

If you want to get a final answer to the `ping/pong timeout error` message, you can run Wireshark on the same system that you are running websocket-client and analyze the packet capture at the time the error occurs. That should tell you the order of ping/pong messages to determine what happened. It would help determine if the issue is the websocket-client code or the network connection.

**Comment by ChristianBEng** [comment] 2021-04-27 09:55
@engn33r today i got an WinError 10054 again. But the while Loop handled the problem.

I logged the Error and the Traceback. Maybe this time the Traceback tells you more about the Issue?

```
wsapp = websocket.WebSocketApp(socketurl_combined,
                               on_open=on_open,
                               on_message=on_message,
                               on_error=on_error,
                               on_close=on_close)

wsapp.last_ping_tm = 32
wsapp.last_pong_tm = 1

while True:
    try:
        # ws.last_ping_tm = 0
        # ws.last_pong_tm = 0
        wsapp.run_forever(ping_interval=40, ping_timeout=30)
    except Exception as e:
        error_logger.exception('ERROR: run_forever()')
        pass
```

> Traceback (most recent call last):
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_app.py", line 349, in run_forever
>     dispatcher.read(self.sock.sock, read, check)
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_app.py", line 71, in read
>     if not read_callback():
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_app.py", line 315, in read
>     op_code, frame = self.sock.recv_data_frame(True)
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_core.py", line 395, in recv_data_frame
>     frame = self.recv_frame()
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_core.py", line 431, in recv_frame
>     return self.frame_buffer.recv_frame()
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_abnf.py", line 372, in recv_frame
>     self.recv_header()
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_abnf.py", line 320, in recv_header
>     header = self.recv_strict(2)
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_abnf.py", line 407, in recv_strict
>     bytes_ = self.recv(min(16384, shortage))
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_core.py", line 514, in _recv
>     return recv(self.sock, bufsize)
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_socket.py", line 113, in recv
>     bytes_ = _recv()
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_socket.py", line 95, in _recv
>     return sock.recv(bufsize)
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1226, in recv
>     return self.read(buflen)
>   File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1101, in read
>     return self._sslobj.read(len)
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by engn33r** [comment] 2021-04-27 14:22
While the new traceback you shared is longer, I don't see any error familiar to me that indicates the root problem. I can suggest two approaches forward. One is to use your current code and add a counter variable in the `while True` loop to determine whether the error occurs on the 2nd, 3rd, or later time that `run_forever()` is run. This might help determine whether there might be a memory issue, threading issue, or something else in play. From there we can try additional efforts to find what is happening. But this approach might not help much and finding the root cause of the issue with your current code might take a lot of time.

The second approach would be to look through old issues and find a more robust solution for what you are trying to do. Issue #580 is one example where using `run_forever()` in threads may offer a better solution than the `while True` loop that you are using. This might require more effort on your part, but it will probably result in a more solid solution.

**Comment by ChristianBEng** [comment] 2021-04-27 14:35
Ok. Thanks a lot so far. For now, I need to test the amount of information from this issue. Since I have only recently started programming and there are still a lot of things that are unclear, I will now spend some time trying to understand your ideas and link them to my problem.
I will keep the issue up to date.

Since my program "works", even if not very professionally, I am satisfied with the situation for now.

**Comment by joelcogen** [comment] 2022-01-29 14:23
To add to your solution, you can use the return of `run_forever` to capture `KeyboardInterrupt` so you can still exit manually:
```
keep_on = True
while keep_on:
  try:
    keep_on = wsapp.run_forever(ping_interval=15, ping_payload=json.dumps({'op': 'ping'}))
  except:
    pass
```
