### ISSUE TITLE
python socket response

### ISSUE THREAD

**Issue by asyncins** [websocket-client/websocket-client#530] opened 2019-02-26 12:58 UTC
I read the source code of websocket-client and decoded the content returned by the server through the recv_frame method. I am not clear about the principle of decoding. But when I decode with recv () and decode ('utf-8') provided in Python documents, I always get an error message:
` UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 0: invalid start byte `

The response content like this:
`b'\x88\x02\x03\xea'`

Can you help me

Thanks

**Comment by engn33r** [comment] 2021-04-01 00:22
This issue looks like a duplicate of #481. As I said for the other issue, I can't provide much help with the information you have shared so far, so please include a [debug log](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) of your WebSocket communications and answer the other questions from [the contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question) if you would like additional help. I will close this issue until (or if) you share additional details.

**Closed by engn33r** 2021-04-01 00:22 UTC
